# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Test'
          script:
            - echo "Your build and test goes here..."
      - step:
          name: 'Lint'
          script:
            - echo "Your linting goes here..."
      - step:
          name: 'Security scan'
          script:
            - echo "Your security scan goes here..."
      - step:
          name: "Build Docker container to Docker Hub"
          services:
            - docker
          script:
            - export DOCKER_BUILDKIT=1
            - docker build -t latest .
            - docker login -u thehobbydeveloper2839 -p $DOCKER_KEY
            - docker tag latest thehobbydeveloper2839/quick-api-tester:latest
            - docker push thehobbydeveloper2839/quick-api-tester:latest
